# Generated by Django 3.2.16 on 2023-04-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
