# Generated by Django 3.2.16 on 2023-04-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0005_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
