# Generated by Django 3.2.16 on 2023-04-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0006_alter_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fisrtname',
            new_name='firstname',
        ),
    ]
