# Generated by Django 3.2.16 on 2023-04-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0007_rename_fisrtname_booking_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Date',
        ),
    ]
