# Generated by Django 3.2.16 on 2023-05-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0008_remove_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
