# Generated by Django 3.2.16 on 2023-05-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0010_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='phno',
        ),
    ]
