# Generated by Django 3.2.16 on 2023-05-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0011_remove_feedback_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
