# Generated by Django 5.0 on 2024-04-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
