# Generated by Django 5.0 on 2024-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0014_booking_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(default='', max_length=254),
        ),
    ]
