# Generated by Django 5.0 on 2024-08-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0017_worker_is_customer_worker_worker_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
