# Generated by Django 5.0 on 2024-08-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0020_alter_worker_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
