# Generated by Django 5.0 on 2024-08-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0022_rename_phno_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
