# Generated by Django 5.0 on 2024-08-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0023_remove_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='name',
        ),
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
