# Generated by Django 5.0 on 2024-08-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0024_remove_worker_name_worker_salary_worker_worker_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='worker_type',
            new_name='worker_Type',
        ),
    ]
