# Generated by Django 5.0 on 2024-08-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0025_rename_worker_type_worker_worker_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='worker_Type',
            new_name='worker_type',
        ),
    ]
