# Generated by Django 5.0 on 2024-08-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0026_rename_worker_type_worker_worker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
