# Generated by Django 5.0 on 2024-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0027_worker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
