# Generated by Django 5.0 on 2024-08-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0028_worker_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='district',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phno',
        ),
        migrations.AddField(
            model_name='booking',
            name='cardnumber',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='salary',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='worker_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
