# Generated by Django 5.0 on 2024-08-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0029_remove_booking_address_remove_booking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
