# Generated by Django 5.0 on 2024-08-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0030_alter_booking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
