# Generated by Django 5.0 on 2024-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0032_alter_worker_worker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
