# Generated by Django 5.0 on 2024-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0033_worker_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
