# Generated by Django 5.0 on 2024-10-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0034_alter_worker_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
