# Generated by Django 5.0 on 2024-10-08 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0035_rename_is_approved_worker_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
